In [32]:
# Import necessary libraries
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, association_rules
import matplotlib.pyplot as plt

# Load dataset
df = pd.read_excel('Online retail.xlsx', header=None)

# Output: Preview the first few rows of the dataset
print("Dataset preview:")
df

C:\Users\Kanta. Sai Dhanush\anaconda3\Latest Anaconda3\Lib\site-packages\openpyxl\packaging\core.py:99: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.datetime.utcnow()
C:\Users\Kanta. Sai Dhanush\anaconda3\Latest Anaconda3\Lib\site-packages\openpyxl\packaging\core.py:99: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  now = datetime.datetime.utcnow()

Dataset preview:

                                                      0
0     shrimp,almonds,avocado,vegetables mix,green gr...
1                                burgers,meatballs,eggs
2                                               chutney
3                                        turkey,avocado
4     mineral water,milk,energy bar,whole wheat rice...
...                                                 ...
7496                      butter,light mayo,fresh bread
7497  burgers,frozen vegetables,eggs,french fries,ma...
7498                                            chicken
7499                                 escalope,green tea
7500    eggs,frozen smoothie,yogurt cake,low fat yogurt

[7501 rows x 1 columns]

In [33]:
#Check for missing values
print("Missing values:")
print(df.isnull().sum())

Missing values:
0    0
dtype: int64

In [34]:
df.describe()

              0
count      7501
unique     5176
top     cookies
freq        223

In [35]:
df.columns = ['Transactions']

In [36]:
# Split the transactions into a list of items
df['Transactions'] = df['Transactions'].apply(lambda x: x.split(','))

In [31]:
# Convert transactions into the required format
te = TransactionEncoder()
te_ary = te.fit(df['Transactions']).transform(df['Transactions'])
data = pd.DataFrame(te_ary, columns=te.columns_)
data

,asparagus,almonds,antioxydant juice,asparagus,avocado,babies food,bacon,barbecue sauce,black tea,blueberries,...,turkey,vegetables mix,water spray,white wine,whole weat flour,whole wheat pasta,whole wheat rice,yams,yogurt cake,zucchini
0,False,True,True,False,True,False,False,False,False,False,...,False,True,False,False,True,False,False,True,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,True,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5171,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5172,False,False,False,False,False,False,False,False,False,False,...,True,False,False,False,False,False,True,False,False,False
5173,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5174,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
5175,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False

In [38]:
# Remove duplicates
df.drop_duplicates(inplace=True)

# Output: Display shape of data after removing duplicates
print(f"Data shape after removing duplicates: {df.shape}")

Data shape after removing duplicates: (5176, 1)

In [40]:
# Apply the Apriori algorithm
frequent_itemsets = apriori(data, min_support=0.01, use_colnames=True)
frequent_itemsets

      support                               itemsets
0    0.029366                              (almonds)
1    0.011206                    (antioxydant juice)
2    0.045981                              (avocado)
3    0.012558                                (bacon)
4    0.015456                       (barbecue sauce)
..        ...                                    ...
433  0.014683  (mineral water, spaghetti, olive oil)
434  0.016615   (mineral water, pancakes, spaghetti)
435  0.012365     (mineral water, shrimp, spaghetti)
436  0.010819       (mineral water, spaghetti, soup)
437  0.013524   (mineral water, spaghetti, tomatoes)

[438 rows x 2 columns]

In [41]:
# Generate the association rules
rules = association_rules(frequent_itemsets, metric="lift", min_threshold=1)

# Display the rules
print(rules.head())

       antecedents      consequents  antecedent support  consequent support  \
0        (almonds)  (mineral water)            0.029366            0.299845
1  (mineral water)        (almonds)            0.299845            0.029366
2      (chocolate)        (avocado)            0.205178            0.045981
3        (avocado)      (chocolate)            0.045981            0.205178
4        (avocado)   (french fries)            0.045981            0.192620

    support  confidence      lift  leverage  conviction  zhangs_metric
0  0.011012    0.375000  1.250644  0.002207    1.120247       0.206476
1  0.011012    0.036727  1.250644  0.002207    1.007641       0.286240
2  0.010240    0.049906  1.085347  0.000805    1.004131       0.098935
3  0.010240    0.222689  1.085347  0.000805    1.022528       0.082426
4  0.011592    0.252101  1.308800  0.002735    1.079531       0.247313

In [42]:
# Display the rules
print("Top 5 rules based on lift:")
print(rules.nlargest(5, 'lift'))

# Sort the rules by confidence and display the top 5
print("\nTop 5 rules based on confidence:")
print(rules.nlargest(5, 'confidence'))

# Sort the rules by support and display the top 5
print("\nTop 5 rules based on support:")
print(rules.nlargest(5, 'support'))

Top 5 rules based on lift:
               antecedents            consequents  antecedent support  \
424    (whole wheat pasta)            (olive oil)            0.040572
425            (olive oil)    (whole wheat pasta)            0.087713
792  (mineral water, milk)                 (soup)            0.067813
797                 (soup)  (mineral water, milk)            0.070904
299          (ground beef)        (herb & pepper)            0.135819

     consequent support   support  confidence      lift  leverage  conviction  \
424            0.087713  0.011012    0.271429  3.094525  0.007454    1.252159
425            0.040572  0.011012    0.125551  3.094525  0.007454    1.097180
792            0.070904  0.012365    0.182336  2.571586  0.007557    1.136281
797            0.067813  0.012365    0.174387  2.571586  0.007557    1.129085
299            0.066461  0.022798    0.167852  2.525588  0.013771    1.121843

     zhangs_metric
424       0.705471
425       0.741925
792       0.655593
797       0.657774
299       0.698989

Top 5 rules based on confidence:
                          antecedents      consequents  antecedent support  \
794                      (milk, soup)  (mineral water)            0.021445
711  (frozen vegetables, ground beef)  (mineral water)            0.024536
830                 (spaghetti, soup)  (mineral water)            0.020672
764           (pancakes, ground beef)  (mineral water)            0.020866
499              (chocolate, chicken)  (mineral water)            0.021252

     consequent support   support  confidence      lift  leverage  conviction  \
794            0.299845  0.012365    0.576577  1.922913  0.005935    1.653557
711            0.299845  0.013331    0.543307  1.811957  0.005974    1.533097
830            0.299845  0.010819    0.523364  1.745448  0.004621    1.468952
764            0.299845  0.010819    0.518519  1.729286  0.004563    1.454167
499            0.299845  0.011012    0.518182  1.728163  0.004640    1.453151

     zhangs_metric
794       0.490474
711       0.459382
830       0.436096
764       0.430714
499       0.430500

Top 5 rules based on support:
         antecedents      consequents  antecedent support  consequent support  \
400  (mineral water)      (spaghetti)            0.299845            0.229521
401      (spaghetti)  (mineral water)            0.229521            0.299845
134      (chocolate)  (mineral water)            0.205178            0.299845
135  (mineral water)      (chocolate)            0.299845            0.205178
186  (mineral water)           (eggs)            0.299845            0.208076

      support  confidence      lift  leverage  conviction  zhangs_metric
400  0.085008    0.283505  1.235204  0.016187    1.075345       0.271965
401  0.085008    0.370370  1.235204  0.016187    1.112010       0.247141
134  0.073223    0.356874  1.190193  0.011701    1.088674       0.201051
135  0.073223    0.244201  1.190193  0.011701    1.051632       0.228235
186  0.070131    0.233892  1.124070  0.007741    1.033698       0.157645

In [44]:
# Display the rules
print("Top 5 rules based on lift:")
print(rules.nlargest(5, 'lift'))

# Sort the rules by confidence and display the top 5
print("\nTop 5 rules based on confidence:")
print(rules.nlargest(5, 'confidence'))

# Sort the rules by support and display the top 5
print("\nTop 5 rules based on support:")
print(rules.nlargest(5, 'support'))

# Further analysis to interpret the results
# Identify frequent antecedents and consequents
frequent_antecedents = rules['antecedents'].value_counts().head()
frequent_consequents = rules['consequents'].value_counts().head()

print("\nMost frequent antecedents:")
print(frequent_antecedents)

print("\nMost frequent consequents:")
print(frequent_consequents)

# Example of interpreting a rule
example_rule = rules.iloc[0]
antecedents = list(example_rule['antecedents'])
consequents = list(example_rule['consequents'])
confidence = example_rule['confidence']
lift = example_rule['lift']

print(f"\nExample Rule Interpretation:\nIf a customer buys {antecedents}, they are likely to buy {consequents} as well.")
print(f"Confidence: {confidence}, Lift: {lift}")

Top 5 rules based on lift:
               antecedents            consequents  antecedent support  \
424    (whole wheat pasta)            (olive oil)            0.040572
425            (olive oil)    (whole wheat pasta)            0.087713
792  (mineral water, milk)                 (soup)            0.067813
797                 (soup)  (mineral water, milk)            0.070904
299          (ground beef)        (herb & pepper)            0.135819

     consequent support   support  confidence      lift  leverage  conviction  \
424            0.087713  0.011012    0.271429  3.094525  0.007454    1.252159
425            0.040572  0.011012    0.125551  3.094525  0.007454    1.097180
792            0.070904  0.012365    0.182336  2.571586  0.007557    1.136281
797            0.067813  0.012365    0.174387  2.571586  0.007557    1.129085
299            0.066461  0.022798    0.167852  2.525588  0.013771    1.121843

     zhangs_metric
424       0.705471
425       0.741925
792       0.655593
797       0.657774
299       0.698989

Top 5 rules based on confidence:
                          antecedents      consequents  antecedent support  \
794                      (milk, soup)  (mineral water)            0.021445
711  (frozen vegetables, ground beef)  (mineral water)            0.024536
830                 (spaghetti, soup)  (mineral water)            0.020672
764           (pancakes, ground beef)  (mineral water)            0.020866
499              (chocolate, chicken)  (mineral water)            0.021252

     consequent support   support  confidence      lift  leverage  conviction  \
794            0.299845  0.012365    0.576577  1.922913  0.005935    1.653557
711            0.299845  0.013331    0.543307  1.811957  0.005974    1.533097
830            0.299845  0.010819    0.523364  1.745448  0.004621    1.468952
764            0.299845  0.010819    0.518519  1.729286  0.004563    1.454167
499            0.299845  0.011012    0.518182  1.728163  0.004640    1.453151

     zhangs_metric
794       0.490474
711       0.459382
830       0.436096
764       0.430714
499       0.430500

Top 5 rules based on support:
         antecedents      consequents  antecedent support  consequent support  \
400  (mineral water)      (spaghetti)            0.299845            0.229521
401      (spaghetti)  (mineral water)            0.229521            0.299845
134      (chocolate)  (mineral water)            0.205178            0.299845
135  (mineral water)      (chocolate)            0.299845            0.205178
186  (mineral water)           (eggs)            0.299845            0.208076

      support  confidence      lift  leverage  conviction  zhangs_metric
400  0.085008    0.283505  1.235204  0.016187    1.075345       0.271965
401  0.085008    0.370370  1.235204  0.016187    1.112010       0.247141
134  0.073223    0.356874  1.190193  0.011701    1.088674       0.201051
135  0.073223    0.244201  1.190193  0.011701    1.051632       0.228235
186  0.070131    0.233892  1.124070  0.007741    1.033698       0.157645

Most frequent antecedents:
antecedents
(mineral water)    83
(spaghetti)        63
(milk)             48
(chocolate)        47
(eggs)             39
Name: count, dtype: int64

Most frequent consequents:
consequents
(mineral water)    83
(spaghetti)        63
(milk)             48
(chocolate)        47
(eggs)             39
Name: count, dtype: int64

Example Rule Interpretation:
If a customer buys ['almonds'], they are likely to buy ['mineral water'] as well.
Confidence: 0.37500000000000006, Lift: 1.2506443298969072

# INTERVIEW QUESTIONS

'''

1. What is lift and why is it important in Association rules?
Lift measures how much more often items A and B occur together than if they were independent.

Importance:
Shows if items are related.
Helps find strong associations.
Aids in business decisions like product placement.

'''

'''

2. What is support and confidence? How do you calculate them?

Support: Frequency of an itemset in all transactions.
Support(𝐴)=Transactions with 𝐴 / Total transactions

Confidence: Likelihood that B is bought when A is bought.
Confidence(𝐴→𝐵)=Transactions with 𝐴 and 𝐵 / Transactions with 𝐴

​'''

'''

3. What are some limitations or challenges of Association rules mining?

Scalability: Hard with large datasets.
Rare Item Problem: Rare items might be missed.
Redundancy: Too many similar rules.
Interpretability: Rules can be confusing.
Overfitting: Rules may fit the sample, not general trends.
Data Quality: Needs clean data to work well.

'''